#!/usr/bin/env python3
"""
Second-pass inspection of ViDoRe V3 Computer Science.

Nothing downloads - it reads the cache fetch_datasets.py already filled.

Open questions:
  Q5  What are the 2 source documents, and what licence do they carry?
  Q6  Were the queries written by humans or generated by a model?
  Q7  What query types / content types exist, and how many of each?
  Q8  Is the benchmark well-formed? (orphan queries, unjudged pages, dupes)
  Q9  What size are the page images?
"""
from collections import Counter

from datasets import load_dataset

REPO = "vidore/vidore_v3_computer_science"


def rule(t):
    print(f"\n{'=' * 70}\n{t}\n{'=' * 70}")


def dist(name, values, top=12):
    """Counter that copes with list-valued columns."""
    c = Counter()
    for v in values:
        if isinstance(v, list):
            c.update(v if v else ["<empty>"])
        else:
            c[v] += 1
    print(f"  {name}  ({len(c)} distinct)")
    for k, n in c.most_common(top):
        print(f"      {str(k)[:56]:<58} {n:>6}")
    if len(c) > top:
        print(f"      ... and {len(c)-top} more")
    return c


# --------------------------------------------------------------- Q5
rule("Q5  The two source documents")
meta = load_dataset(REPO, "documents_metadata")["test"]
for row in meta:
    print()
    for k, v in row.items():
        print(f"  {k:<16}: {str(v)[:160]}")

# --------------------------------------------------------------- Q6/Q7
rule("Q6  Who or what wrote the queries?")
q = load_dataset(REPO, "queries")["test"]
for col in ("query_generator", "query_generation_pipeline", "source_type"):
    if col in q.column_names:
        dist(col, q[col])
        print()

print("  --- five verbatim queries ---")
for i in range(5):
    print(f"   [{q[i]['query_id']}] {q[i]['query']!r}")

rule("Q7  Query taxonomy")
for col in ("query_types", "query_format", "content_type",
            "query_type_for_generation", "language"):
    if col in q.column_names:
        dist(col, q[col])
        print()

# --------------------------------------------------------------- Q8
rule("Q8  Is the benchmark well-formed?")
corpus = load_dataset(REPO, "corpus")["test"]
qrels = load_dataset(REPO, "qrels")["test"]

qids_q = set(q["query_id"])
qids_r = set(qrels["query_id"])
cids_c = set(corpus["corpus_id"])
cids_r = set(qrels["corpus_id"])

print(f"  queries declared            : {len(qids_q)}")
print(f"  queries with >=1 judgement  : {len(qids_r)}")
print(f"  ORPHAN queries (no qrels)   : {len(qids_q - qids_r)}   <- unfindable; excluded from recall")
print(f"  qrels pointing at nothing   : {len(qids_r - qids_q)}")
print()
print(f"  corpus pages                : {len(cids_c)}")
print(f"  pages judged relevant to >=1: {len(cids_r & cids_c)}")
print(f"  pages NEVER relevant        : {len(cids_c - cids_r)}   <- pure distractors")
print(f"  qrels citing missing pages  : {len(cids_r - cids_c)}")
print()
per_q = Counter(qrels["query_id"])
vals = sorted(per_q.values())
print(f"  relevant pages per query    : min={vals[0]} median={vals[len(vals)//2]} max={vals[-1]}")
print(f"  duplicate (query,page) pairs: "
      f"{len(qrels) - len(set(zip(qrels['query_id'], qrels['corpus_id'])))}")

print("\n  --- content_type of judgements (drives the SigLIP-vs-BM25 split) ---")
dist("qrels.content_type", qrels["content_type"])

# --------------------------------------------------------------- Q9
rule("Q9  Page images and provided text")
sizes = Counter()
for i in range(0, len(corpus), max(1, len(corpus) // 60)):
    sizes[corpus[i]["image"].size] += 1
print("  sampled image sizes (w,h):")
for s, n in sizes.most_common(8):
    print(f"      {str(s):<18} {n}")

md = corpus[0]["markdown"]
print(f"\n  markdown column present: {md is not None}")
if md:
    lens = [len(corpus[i]["markdown"] or "") for i in range(0, len(corpus), 20)]
    lens.sort()
    print(f"  markdown length chars  : min={lens[0]} median={lens[len(lens)//2]} max={lens[-1]}")
    print(f"\n  --- first 400 chars of page {corpus[0]['corpus_id']} ---")
    print("  " + md[:400].replace("\n", "\n  "))

print("\nPaste this back to Claude.")
